module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '@common/(.*)': '<rootDir>/common/$1',
    '@config/(.*)': '<rootDir>/config/$1',
    '@guards/(.*)': '<rootDir>/guards/$1',
    '@exceptions/(.*)': '<rootDir>/exception-filters/$1',
    '@middleware/(.*)': '<rootDir>/middleware/$1',
    '@strategies/(.*)': '<rootDir>/strategies/$1',
    '@providers/(.*)': '<rootDir>/providers/$1',
    '@decorators/(.*)': '<rootDir>/decorators/$1',
    '@shared/(.*)': '<rootDir>/shared/$1',
    '@logger/(.*)': '<rootDir>/logger/$1',
    '@auth/(.*)': '<rootDir>/modules/auth/$1',
    '@users/(.*)': '<rootDir>/modules/user/$1',
    '@roles/(.*)': '<rootDir>/modules/role/$1',
    '@role-permission/(.*)': '<rootDir>/modules/role-permission/$1',
    '@permissions/(.*)': '<rootDir>/modules/permission/$1',
    '@user-role/(.*)': '<rootDir>/modules/user-role/$1',
  },
};
