import { Log } from '../enums/log.enum';

/**
 * Log description is supported for mapping description when using GraphQL
 */
export const LOG_DESCRIPTION: Record<Log, string> = {
  [Log.eventLogs]:
    'An event log is a high-level log that records network traffic and usage data such as incorrect password attempts, login attempts, and application events.',
  [Log.serverLogs]: 'A server log is a text document that keeps track of actions on a certain server over some time.',
  [Log.systemLogs]:
    'A system log, often known as Syslog, is a log of events that occur in the operating system. Startup notifications, system modifications, unexpected shutdowns, failures and warnings, and other critical procedures are all included. Syslogs are generated by Windows, Linux in the log directory, and macOS.',
  [Log.authorizationAndAccessLogs]:
    'Authorization and access logs contain a list of persons or bots who have accessed specific programs or files.',
  [Log.changeLogs]: 'A change log is a list of all the modifications made to an application or file over time.',
  [Log.availabilityLogs]: 'System performance, uptime, and availability are all tracked in availability logs.',
  [Log.resourceLogs]: 'Connectivity difficulties and capacity restrictions are recorded in resource logs.',
  [Log.threatLogs]:
    "Threat logs are logs that contain information on the system, file, or application traffic that matches a firewall's security profile.",
};
